### ISSUE TITLE
`wf_requests_batch()` accepts requests that overwrite each other

### ISSUE THREAD

**Issue by eliocamp** [bluegreen-labs/ecmwfr#100]
A friend of mine (definitely not me :rofl: ) sent a bunch of requests but forgot to change the filename in the `target` slot, so `wf_requests_batch()`  downloaded every request in the same filename, which was a total waste of everyone's time. 

Should the function check for this issue and error out early? My gut tells me it should, since I don't see any situation in which the user would want `wf_requests_batch()` to overwrite requests.

**Comment by khufkens** [comment]
Yep, probably best to do some checks. Grab all filenames and `if (any(duplicated(filenames))) {}` should do the trick.

**Comment by eliocamp** [comment]
There. 

I've just noticed that this is issue 100! :tada:

**Comment by khufkens** [comment]
Wonderful, will push this to CRAN next week or so. Stuff is piled high and deep for the moment.
