### ISSUE TITLE
batch requests: Send a new request as soon as one is downloaded

### ISSUE THREAD

**Issue by eliocamp** [bluegreen-labs/ecmwfr#105]
The way the queue system is implemented now, once one requests is finished and downloaded, the code then checks the next request instead of immediately sending a new request. In practice requests will probably finish processing at roughly the same time, so the function will download one after the other until it stops and then send the new requests. It would be more time efficient to send a new request each time one is downloaded so it can start being processed while the code downloads the next. 

I hope this is clear enough. 🤣

**Comment by khufkens** [comment]
Personal notes, but read along if helpful.

Trying to resolve this as it is slowing my work down. Some context, I'm running a large job of small subsets (site based) searches for hourly cloud cover data. Generally jobs are small (~100kb max) but traverse the time axis for a long time (decade). Batch processing stalls on the above error after variable times. This breaks the routine / downloads.

I have a hunch that I'm getting kicked off the server or the timings are off, generating an edge case which is not captured in the current setup. 

To prevent frequent polling of the API using the batch routine I've put in a `Sys.sleep(3)` in the while loop to slow things down. I'll run with this and see how far I get in this instance.

**Comment by khufkens** [comment]
So, well that didn't work. So it ain't an issue with spamming the API. I'm wondering if we miss one of the html codes in processing. Basically the error states that `private$status` doesn't exist (or is empty, i.e. wasn't assigned somewhere).

So, if here:
https://github.com/bluegreen-labs/ecmwfr/blob/c3e0e8f365bf8431c3e0dbb0a6d1a8f270643e1d/R/service-cds.R#L50

Nothing gets assigned for some reason, things fall apart.

**Comment by khufkens** [comment]
Long requests at time stall on:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Error in the HTTP2 framing layer
```

Not the argument of length zero error anymore though.

**Comment by khufkens** [comment]
The above seems to be related to new support in curl (httr) for http2, which is automatically enabled.

https://github.com/r-hub/rhub/issues/19

Can be set manually with: `httr::config(http_version = 2)` or in this case probably should be:
`httr::set_config(httr::config(http_version = 0))` 
to avoid the error

**Comment by RonEfrat** [comment]
> Might be related, when using batch requests I get this error at times:
> 
> ```r
> No encoding supplied: defaulting to UTF-8.
> Error in if (private$status == "completed") { : 
>   argument is of length zero
> ```
> 
> This might suggest some offset timing in checking the status (with the element not being there anymore).
> 
> Just writing this down for reference. I've had a hard time debugging this. Anyway, will get to this if I've more time.

Thanks for the amazing package! 
Did you find any solution for the issue above?
