### ISSUE TITLE
Daily averages using CDS API

### ISSUE THREAD

**Issue by ainsliej** [bluegreen-labs/ecmwfr#107]
Hi there,

I was wondering whether it was possible to access the [Daily Averages ERA-5 data](https://datastore.copernicus-climate.eu/documents/app-c3s-daily-era5-statistics/C3S_Application-Documentation_ERA5-daily-statistics-v2.pdf) from the CDS API using the package? 

I have tried adding the 'statistic' parameter to the request, but it returns an error message "Ambiguous parameter: statistic could be STEP or STYLE". 

Thanks for making such a great package, its been so useful to me!

**Comment by khufkens** [comment]
Sorry for the late response, holidays and all.

This isn't really a true data product (reading the linked document), this is a workflow on the CDS machines (using hourly data) for which the daily summary values are then returned for download. Note the different API call they use `c.service()` instead of `c.retrieve()` as for normal data.

I've not considered the option of using these workflows in addition to basic requests for data. I'm not sure this will work, but I'll see if I can make this work. In any case this might remain an niche feature as pretty advanced.

I'll look into it.

**Comment by khufkens** [comment]
@ainsliej It seems the functionality is exposed via the normal API, so this could be made functional.

The below code (for personal reference mostly) shows the retrieve call, currently used. Below is the service call and API endpoints used. I'm unsure what is returned as 'result', but I guess this will be a URL for downloading data. Anyway, supporting workflows should be possible.

```python
    def retrieve(self, name, request, target=None):
        result = self._api("%s/resources/%s" % (self.url, name), request, "POST")
        if target is not None:
            result.download(target)
        return result

    def service(self, name, *args, **kwargs):
        self.delete = False  # Don't delete results
        name = "/".join(name.split("."))
        mimic_ui = kwargs.pop('mimic_ui', False)
        # To mimic the CDS ui the request should be populated directly with the kwargs
        if mimic_ui:
            request = kwargs
        else:
            request = dict(args=args, kwargs=kwargs)

        if self.metadata:
            request["_cds_metadata"] = self.metadata
        request = toJSON(request)
        result = self._api(
            "%s/tasks/services/%s/clientid-%s" % (self.url, name, uuid.uuid4().hex),
            request,
            "PUT",
        )
        return result
```

I'll first try to get a mock example to work, and will proceed from there. Will keep you posted on progress here.

@eliocamp read along if interested, I might need your input in implementing the workflow method in the R6 classes.

**Comment by khufkens** [comment]
The below example works and generates daily mean temperatures for the January 2020. Note that you have to cycle through months as per example (pdf you linked to). Querying multiple months, or a single day by using an additional "day" parameter does not work.

```r
library(ecmwfr)
library(terra) # to visualize things

# set your user ID
user <- "YOUR_CDS_ID"

# get key (as normally - hidden from users)
key <- wf_get_key(user = user, service = "cds")

# This query works
# single month of mean daily temperature
request = list(
  "args" = "",
  kwargs = list(
    params = list(
      kwargs = list(
        "dataset" = "reanalysis-era5-single-levels",
        "product_type" = "reanalysis",
        "variable" = "2m_temperature",
        "statistic" = "daily_mean",
        "year" = "2020",
        "month" = "01",
        "time_zone" = "UTC+00:0",
        "frequency" = "1-hourly",
        "grid" = "0.25/0.25",
        "area" = list(
          lat = list(38, 60),
          lon = list(-20,20)
        )
      ),
      "workflow_name" = "application",
      "realm" = "c3s",
      "project" = "app-c3s-daily-era5-statistics",
      "version" = "master"
    )
  )
)

# Get the response for the query provided
# from the correct endpoint
response <- httr::PUT(
  sprintf(
    "%s/tasks/services/%s/clientid-%s",
    ecmwfr:::wf_server(service = "cds"),
    gsub("\\.", "/","tool.toolbox.orchestrator.workflow"),
    uuid::UUIDgenerate(output = "string")
  ),
  httr::authenticate(user, key),
  httr::add_headers("Accept" = "application/json",
                    "Content-Type" = "application/json"),
  body = request,
  encode = "json"
)

# The returned content, this is not the data
# only where to get the data if successful
ct <- httr::content(response)
print(ct)

# You can reconstitute the URL where to download things
# as such
url <- ecmwfr:::wf_server(id = ct$request_id, service = "cds")

# update the response to see if the download
# is available (you can check this on the CDS page)
# but in the package for normal requests this query
# is cycled until "completed", see below
response <- httr::GET(
  url,
  httr::authenticate(user, key),
  httr::add_headers("Accept" = "application/json",
                    "Content-Type" = "application/json"),
  encode = "json"
)

# grab content from response
ct <- httr::content(response)

# if the response states that it is completed
# grab the location from the response element and
if (ct$state == "completed") {
  download.file(
    ct$result[[1]]$location,
    "./test.nc"
  )
}

r <- terra::rast("./test.nc")
terra::plot(r)
```

**Comment by khufkens** [comment]
@eliocamp see above, this solution works and should be relatively easily integrated into the existing R6 framework as it follows the workflow almost to the letter. Only the file location is embedded into a deeper list level as per ct$result[[1]]$location above.

Took some data sleuthing in the python `cdsapi` but generally an easy fix. Thanks @ainsliej for pointing me to this.

**Comment by khufkens** [comment]
@eliocamp I only think the stuff listed in the document will be supported, this is not a general purpose endpoint. But it provides a fair number of products to summarize.

As I understand it the endpoint really taps into some backend runner, which does the work (given forwarded application parameters) and then dumps data into the CDS requests framework for managing data egress (downloads).

Technically you should be able to tap into other applications (on the CDS website) and grab output data as well (if you know how to format the parameter correctly, and how the app is named).

**Comment by khufkens** [comment]
To be specific, the below settings (as included in the query) specify it is an application, which needs to be downloaded from the realm (gitlab account as far as I could tell from debugging) and grab the repository `app-c3s-daily-era5-statistics` and the master branch of it.

```r
      "workflow_name" = "application"
      "realm" = "c3s"
      "project" = "app-c3s-daily-era5-statistics"
      "version" = "master"
```

**Comment by eliocamp** [comment]
Ah. So someone creates an application in the CDS thingy and then you can query it with this code? So this code uses a specific application that computes averages?

**Comment by khufkens** [comment]
Exactly! Technically if you create an App online in the [CDS toolbox editor](https://cds.climate.copernicus.eu/toolbox-editor/2) you should be able to query the output via these means as well if you can figure out the bits and bops of interfacing. But, the source code for the above example is online so this shouldn't be too hard.

https://cds.climate.copernicus.eu/cdsapp#!/software/app-c3s-daily-era5-statistics?tab=appcode

This opens top opportunity to implement point wise data extraction! Which currently isn't easily done using the default API.

**Comment by eliocamp** [comment]
Very interesting! I'm not thinking about creating specific R packages to get preprocessed data using idiomatic code with ecmwfr as the backend... but I digress.  

So would be a new `wf_application()` or something else? Is there a GUI to select all the parameters and get code that we can then automatically translate to R code like we do with the requests? Or will the user need to understand a bit more about each specific application to build a valid request?

**Comment by khufkens** [comment]
There is a GUI but only that, it doesn't return an API query explicitly. I guess the closest thing would be to copy the URL once all parameters are set. Obviously if you only need one dataset you can then just punch download, but the point is to automate these things (if not using constructor functions).

This is the GUI:
https://cds.climate.copernicus.eu/apps/user-apps/app-c3s-daily-era5-statistics

The url will set the defaults, or settings and can be parsed I guess - this would be the easiest way to avoid user input errors (which are the most common issues listed here).

We can fold this into `wf_request()` or keep it separate for now, and see where it goes or how far we can stretch this. I think it has potential (as you can move some compute to ECMWF servers).

**Comment by eliocamp** [comment]
Yeah, no, this needs to be a more generic support for any application, I think. 

>  I guess the closest thing would be to copy the URL once all parameters are set.

That might do it, but is this generic enough for any application or is it specific for this one?

**Comment by eliocamp** [comment]
This would be like creating a new anonymous application on the fly, wouldn't it? This is even more advanced. 

I think this could be supported in a new function `wf_cds_application()` or something like that. One of the arguments would be the application, which could be an application name or the code (or, even better, a file that holds the code, since having the code inside a single string is very unwieldy). 

I'm a bit confused on the difference between this:

```r
request = list(
  "args" = "",
  kwargs = list(
    params = list(
      kwargs = list(
        "dataset" = "reanalysis-era5-single-levels",
        "product_type" = "reanalysis",
        "variable" = "2m_temperature",
        "statistic" = "daily_mean",
        "year" = "2020",
        "month" = "01",
        "time_zone" = "UTC+00:0",
        "frequency" = "1-hourly",
        "grid" = "0.25/0.25",
        "area" = list(
          lat = list(38, 60),
          lon = list(-20,20)
        )
      ),
      "workflow_name" = "application",
      "realm" = "c3s",
      "project" = "app-c3s-daily-era5-statistics",
      "version" = "master"
    )
  )
)
```

which seems to have all the parameters inside the first `kwargs` element.

And this

```r
request = list(
      code = code,
      kwargs = list(
        "lat" = 43,
        "lon" = 75,
        "var" = "Near-Surface Air Temperature"
      ),
      "workflow_name" = "plot_time_series"
    )
```

which has the parameters as the top-level elements of the list. Does the format of the request depend on the application?

**Comment by khufkens** [comment]
Different endpoints!

The first one runs on:
`tool.toolbox.orchestrator.workflow`

and side loads a git repo as far as I could tell from debugging

the second one runs the code in `code` clean at:
`tool.toolbox.orchestrator.run_workflow` # note RUN there

And yes, you could create anonymous functions on the fly like this.

**Comment by khufkens** [comment]
And to answer your question last question, the format between the fully exposed workflows and the ones you forward to the cds toolbox editor are a bit different. I'm also not aware of how many "normal" workflows there are (formally released by ECMWF). Obviously you can code infinite "run_workflows".

**Comment by khufkens** [comment]
For reference, the formal python `cdsapi` parses these workflows and depending on the input queries the correct input. I guess it would be best to aim for something similar. In case of forwarding code, where the code comes from should be flexible indeed.

**Comment by khufkens** [comment]
The ones you link with docs are formal and run on the normal `workflow`. Question is if they all document their parameters well and if they return data, rather than figures and maps (seems to be a lot of the latter). Not sure if you can grab figures as well as data.

You can write whatever for the toolbox editor I think, if it runs there it runs from the API I think on `run_workflow`.

**Comment by khufkens** [comment]
I pushed my demo code to an `analysis` folder:

https://github.com/bluegreen-labs/ecmwfr/tree/master/analysis

I would suggest, have a look. This should explain a lot. And you can mess with things.

Seems like some of the `workflow` applications are embedded and out of reach :disappointed:

**Comment by eliocamp** [comment]
I noticed that you can copy the source code, put it in the `code` variable and use the run_workflow endpoint. 

I grabbed [this code](https://cds.climate.copernicus.eu/cdsapp#!/software/app-c3s-daily-era5-statistics?tab=appcode), saved it in a file era5.py and then used this code in the test_run_workflow.R script. 

```r

code <- readLines("analysis/era5.py") |>
  paste0(collapse = "\n")

# This query works
# single month of mean daily temperature
request = list(
      code = code,
        kwargs = list(
          "dataset" = "reanalysis-era5-single-levels",
          "product_type" = "reanalysis",
          "variable" = "2m_temperature",
          "statistic" = "daily_mean",
          "year" = "2020",
          "month" = "01",
          "time_zone" = "UTC+00:0",
          "frequency" = "1-hourly",
          "grid" = "0.25/0.25",
          "area" = list(
            lat = list(38, 60),
            lon = list(-20,20)
          )
      ),
      "workflow_name" = "application"
    )
```

And it seemed to work. 

I suspect that might make the code more reproducible since it doesn't depend on the remote application code. It might also make it a bit easier to create the request format, without all the nested list. Just the code and the arguments. 

Then, it sees like the only difference with the basic request is the http verb and the URL. Right? 

So to support the run_workflow thing we would only need to implement this part:

```r
response <- httr::PUT(
  sprintf(
    "%s/tasks/services/%s/clientid-%s",
    ecmwfr:::wf_server(service = "cds"),
    # NOTE THE DIFFERENENT ENDPOINT FOR TOOLBOX EDITOR APPS
    gsub("\\.", "/","tool.toolbox.orchestrator.run_workflow"),
    uuid::UUIDgenerate(output = "string")
  ),
  httr::authenticate(user, key),
  httr::add_headers("Accept" = "application/json",
                    "Content-Type" = "application/json"),
  body = request,
  encode = "json"
)
```

Oh, and also remove a lot of the logic used to validate the datasets and search for the correct username and stuff.

**Comment by khufkens** [comment]
Yep, this makes sense. The app they put online running the CDS Toolbox code, only exposed differently. 

This could indeed save us the hassle of dealing with a gazillion workflows etc. Just implementing the `run_workflow` setup would cover most use cases then. Cool stuff.

**Comment by eliocamp** [comment]
And it's true that almost all applications return some kind of interactive figure (or "livefigure"), so it's not really applicable to what this package does. 

I can try to add support for this. 

I can create a `cds_workflow` object that inherits from `cds_service` and only changes the http verb and the URL.

**Comment by khufkens** [comment]
I'm calling it a day at my end. See where you get, but no rush. This has been sort of a happy accident stumbling upon this.

Drop me a line here if I need to pick something up tomorrow morning (I've got an hour long commute to fill), if not I'll have a go at it in a new branch (will let you know).

**Comment by khufkens** [comment]
Ah, a true scholar I see :)
