### ISSUE TITLE
wf_transfer failed actually stops loops.

### ISSUE THREAD

**Issue by martindoublem** [bluegreen-labs/ecmwfr#115]
Hi there,

Just wondering if there was a way when the wf_transfer function fails, that instead of having a hard stop, like implemented currently, if we could just return a fail, condition but not a stop.

I could actually program this functionality and implement it and submit a PR and you could decide if this is actually interesting.

Thank you in advance for all of your help.

**Comment by eliocamp** [comment]
I kind of thought this was implemented already. This at least should be an option for batch requests (one single fail requests shouldn't make the rest stop). 

For now, you can always wrap your calls with `try()` or use `purrr::safely()` or `purrr::posibly()`.

**Comment by khufkens** [comment]
`wf_request()` returns a `stop()` and needs to be wrapped by `try()` or similar indeed, or rely on `wf_request_batch()` to have flexible batch downloads with proper error trapping on multiple downloads.

I'm reluctant to move this to a `warning()` as this isn't really the case. A `stop()` is invoked when the desired behaviour is not met, complete fail, a `warning()`  should be invoked if some desired output is returned but might be "unexpected" and needs clarification.

Always separate data requests from further processing, this should limit the fallout of not wrapping things in a `try()` routine. In addition it doesn't place too much burden onto the CDS servers.
