### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by jmertic** [bluegreen-labs/ecmwfr#119]
Hi! I'm looking to add this project to the LF Energy Landscape ( l.lfenergy.org ) and was wondering if you had a pure SVG version of the logo. If you have an EPS or AI version that works too. Thanks!

**Comment by khufkens** [comment]
Sorry for the late reply. Fixed as per:

https://github.com/bluegreen-labs/ecmwfr/commit/14e8e3da23f7aa85a5c58d700fee32e6dba6a147

You can find it in the root of the repo

**Comment by jmertic** [comment]
This looks great! Thank you!
