### ISSUE TITLE
Errore: Data identifier cems-fire-historical-v1 is not found in Web API, CDS or ADS datasets.                  Or your login credentials do not match your request.

### ISSUE THREAD

**Issue by alextaf2017** [bluegreen-labs/ecmwfr#126]
Goodmorning, this is my script taken from web api and already transformated python to list in R:
# load the library
library(ecmwfr)
library(ncdf4)
library(terra)
library(maps)

wf_set_key("285996", "xxx","cds")                                                                                           
                                                                                              
request <- list(
  product_type = "reanalysis",
  variable = c("build_up_index", "burning_index", "fire_danger_index", "ignition_component", "initial_fire_spread_index"),
  dataset_type = "consolidated_dataset",
  system_version = "4_1",
  year = "2022",
  month = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"),
  day = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"),
  grid = "0.25/0.25",
  format = "netcdf",
  area = c(47.04, -6.37, -35.29, 18.31),
  dataset_short_name = "cems-fire-historical-v1",
  target = "download.nc"
)
request
ncfile <- wf_request(
  user = "285996",
  request = request,
  transfer = TRUE,
  path = "~",
  verbose = FALSE
  )
It gives me always this error, i cannot find the solution, I tried different ways. A few days ago I tried with sucess to download another datasets, but in this case not

**Comment by khufkens** [comment]
There are lots of things changing at the API side, see issue #128.

Basically, I don't think I can help you in the near term. 

Use the web interface to download the data if this is a singular request. Chances are that with the migration of the API the package will break profoundly before I find what is holding things back in the current setup. Apologies.
