### ISSUE TITLE
Migration CDS/ADS -- anticipated package failure

### ISSUE THREAD

**Issue by khufkens** [bluegreen-labs/ecmwfr#128]
This spring the whole CDS/ADS framework will be redone. Aside from this very brief communication:

https://confluence.ecmwf.int/display/CKB/Please+read%3A+CDS+and+ADS+migrating+to+new+infrastructure%3A+Common+Data+Store+%28CDS%29+Engine

There is little information on the structure and or general setup of the new API. There is no way to anticipate changes, which seem to be profound in some cases (full reset accounts). This might break the package profoundly.

@eliocamp

**Comment by eliocamp** [comment]
Oof.. annoying. With luck, a lot of the package code can be reused and adapted. It would be nice to have a date, and also a test server to prepare changes..

**Comment by khufkens** [comment]
There is nothing there to work with I'm afraid. Hope this won't be to much of a change. I'll keep an eye out for a press release, but with no set deadline this is rather difficult. Ping me here or on Mastodon should you see something on an update.

**Comment by khufkens** [comment]
Beta API endpoint: https://cds-beta.climate.copernicus.eu/api - to validate functionality (will start new branch)

**Comment by khufkens** [comment]
See #131 - waiting for press release for roll-out

**Comment by khufkens** [comment]
Addin needs to be accomodated for the new API format specs on the CDS (beta) website - separate entry for transition (no set date on depreciation of the old CDS and or website migration).

## NEW
dataset = "reanalysis-era5-land"
request = {
  'variable': ['2m_temperature'],
  'year': '2024',
  'month': '01',
  'day': ['01'],
  'time': ['00:00'],
  'data_format': 'netcdf'
}

## OLD
c.retrieve(
  'reanalysis-era5-land',
  {
    'variable': '2m_temperature',
    'year': '2024',
    'month': '01',
    'day': '01',
    'time': '00:00',
    'format': 'netcdf',
  },
  'download.nc')
