### ISSUE TITLE
keyring and libsodium - suggests <> import

### ISSUE THREAD

**Issue by khufkens** [bluegreen-labs/ecmwfr#142]
@eliocamp 

I'm currently putting {keyring} in suggests. But I'm really not a fan of the current implementation of environmental variables as a way to use keys. Basically this is super poor practice. Leaking API keys from plain text files and set environmental variables in scripts one of the main issues on places like this.

How hard was it to get libsodium to work on an HPC on your end? To my understanding this is a fairly common open source library which shouldn't be hard to side load on most clusters.

**Comment by eliocamp** [comment]
I would need to ask the admins to install it. I could try that and tell you how it went :P

**Comment by khufkens** [comment]
I've pushed ahead with keyring in imports, but the system environment setting is still there. So, you should be able to move it to suggests and compile from source to get going. I decided against it as it encourages poor security practices (if you make it explicitly available people will use the "easiest" option etc).
