### ISSUE TITLE
rOpenSci review + (JOSS) paper

### ISSUE THREAD

**Issue by khufkens** [bluegreen-labs/ecmwfr#24]
Currently functionality is good, and working toward the [ecmwfrExtra](https://github.com/khufkens/ecmwfrExtra) will provide considerable context, and worked examples, so writing a paper will be easier (or vice versa). It might be time to think about how to move forward with this. Thoughts, @jwagemann @eliocamp @retostauffer?

## worked examples + data integration

From my part I have these ideas:
- phenology modelling which include temperature + precip. variables
- bird migration + wind interactions (recent request by birding friend), includes wind and altitude differences in processes.

**Comment by eliocamp** [comment]
I don't have any simple examples handy at the moment. I've used the data for a paper I'm preparing that I think is too inside baseball.

Here's an idea that might be a stretch: would it be possible to have this package listed in the ECMWF webpage in some capacity? Probable not, because it would mean a level of official support they are probably not willing to give willy nilly. But maybe?

**Comment by khufkens** [comment]
@eliocamp I was looking at your metR package and thought it would make a fitting example, visualizing things. Even more so as I was dealing with wind data the past week for my birding friend (calculating least resistance flight paths using windr etc). Endorsement by ECMWF will likely not happen due to liabilities etc. But, might be worth a shot at some point (certainly past a next release).

**Comment by retostauffer** [comment]
Hy @khufkens 
I thought about it for few days now. Not yet sure what would be a nice but not too complicated example.

- grid-point wise trend estimates (surface temperature; monthly/annual mean); spatial plot of the trend/significance of the trend. Problem: linear trends would be efficient but not accurate from a scientific point of view. Thus, maybe not a good example.
- calculation of atmospheric teleconnection indices like NAO, AO, ... (mainly surface pressure)
- time series reconstruction (fill missing data) in a time series using simple multiple linear regression approach
- trend analysis for hot days (e.g., exceeding 35+) using poisson regression or binomial models

These things would not be too tricky to write, but may be too simple from a scientific perspective (state of the art research). Thus, I am not sure whether or not one should use such illustrative but simplified examples?

All best,
R

**Comment by eliocamp** [comment]
I can do some simple visualisation examples with regression maps and the like. I'll add some principal component calculations.

**Comment by khufkens** [comment]
Hi @retostauffer, @eliocamp these are all wonderful examples!

I would argue that cutting edge research is not needed - too hard to keep up with things anyway. I think the point would be to provide a starting point for analysis and code development. So thinking about intermediate data to analysis might also be helpful (say a general threshold based function - or how to efficiently tackle this). So although the trend estimation might not be perfect I think it is still a good starting point for most, and still valid (with a bit of a disclaimer). The rest of the examples are also wonderful.

**Comment by eliocamp** [comment]
Where should this examples be located? Vignettes should be the obvious place, but then we should add the extra tools needed for analysis as dependencies (in suggests).

**Comment by khufkens** [comment]
If things are more substantial in terms of custom functions I would suggest to put them in the ecmwfrExtra repo (https://github.com/khufkens/ecmwfrExtra) together with any proposals written to gather support. The vignettes in the ecmwfr package should cover basic usage, simple long term means etc would still be ok (i.e. how is the data structured and how do I query a subset). 

The moment you hit more complex cases things will get muddy, best to put it elsewhere with a proper introduction to the problem (meteorological, hydrological, ecological etc).

This would also allow to borrow some visuals from these vignettes and show some initial code development in any dependent proposals (as the one in place or maybe in the future for other work). Not sure it applies, but feel free to run with the idea elsewhere as well.

**Comment by eliocamp** [comment]
Perfect. I'll PR that repo with examples, then!
