### ISSUE TITLE
encouraging pkg citation 

### ISSUE THREAD

**Issue by benmarwick** [bluegreen-labs/ecmwfr#61]
Just saw your [tweet](https://twitter.com/koen_hufkens/status/1261270236520689664), and fully agree with your concerns. I've had success getting citations of my software by making it clear to users that it is expected, and making it easy for them to do it. For example, make it the first thing people see on the README and in the vignette, like this:  

# ecmwfr 

[![Build Status](https://travis-ci.org/khufkens/ecmwfr.svg?branch=master)](https://travis-ci.org/khufkens/ecmwfr)  other badges, etc.

Programmatic interface to the two [European Centre for Medium-Range Weather Forecasts](https://www.ecmwf.int/) API services. The package provides easy access to the ['ECMWF' web API services](https://confluence.ecmwf.int/display/WEBAPI/ECMWF+Web+API+Home)
and Copernicus [Climate Data Store](https://cds.climate.copernicus.eu) or 'CDS' from within R, matching and expanding upon the ECMWF python tools.

## How to cite this package in your article

You can cite this package like this "we obtained data from the European Centre for Medium-Range Weather Forecasts API using the ecmwf R package (Hufkens, Stauffer, and Campitelli 2019)".

Here is the full bibliographic reference to include in your reference list (don't forget to update the 'last accessed' date):

> Hufkens, K., R. Stauffer, & E. Campitelli. (2019). ecmwfr: Programmatic interface to the two European Centre for Medium-Range Weather Forecasts API services. (Version v1.2.0). Zenodo. http://doi.org/10.5281/zenodo.2647541. Last accessed 15 May 2020

### stable release

To install the current stable release use a CRAN repository:

``` r
install.packages("ecmwfr")
library("ecmwfr")
```

**Comment by khufkens** [comment]
Will fix this for sure. I generally put a citation at the bottom of the page, but I guess that's a research habit and maybe some false modesty.

Seems like you and others have had more success with this approach.
