### ISSUE TITLE
Add support for ADS?

### ISSUE THREAD

**Issue by philament** [bluegreen-labs/ecmwfr#66]
Hi, very nice package! Are there any plans to add support for the Atmosphere Data Store (https://ads.atmosphere.copernicus.eu/)? It appears to use exactly the same Python interface as the Climate Data Store, so I assume it should be quite straightforward to implement. Or maybe this is already possible, but my attempts to retrieve ADS data failed so far.

**Comment by khufkens** [comment]
Hi @philament,

Thanks, and I will look into it. 

CAMS, until recently it seems, ran of a different API so I didn't consider it (the API was not really an a formal API - which would result in a hack of a solution with the burden with me rather than with them in maintaining this pseudo-API).

Seems they migrated to CDS so it should be easy to adjust if I can find all the docs, which has been difficult for CDS as well (the API is documented on the python toolbox level not the true API level - i.e. OpenAPI based stuff). They use the CDS authentication so only one account is required, only the correct endpoint needs to be set (and products validated).

Will keep you posted.
K

**Comment by khufkens** [comment]
Merged my local hotfix branch and pushed to github.
Local checks run fine but until I've ran this through its paces this might barf at any time.

https://github.com/bluegreen-labs/ecmwfr/commit/ddd6a595cc5d3cdaecac3d5f8d953445b2dffb55

There will be a formal release later, until then feel free to try downloads. Some products seem to be missing or can't be validated through the product list and are hence not available.

**Comment by khufkens** [comment]
Obviously, reinstall from github for the latest fixes.

**Comment by khufkens** [comment]
Also, you do need a new API key from ADS. There is not cross service authentication. Which I'm rather disappointed about. The rest remains functionally the same WRT how the CDS bit works. Python conversion addin should work as well.

**Comment by philament** [comment]
Wow, that was quick! Thanks for taking a look at this. I am eager to give it a try. I installed the latest version from github but am struggling a bit with the ADS authentication. It works fine for CDS but for ADS I get a certificate error:

```
> wf_set_key(user = "xxxxx",key = '554bf3c2-c988-45a3-b4d5-xxxxxxxxxxxx', service = 'cds')
User xxxxx for cds service added successfully in keychain
> wf_set_key(user = "xxxx",key = 'cf177234-ef8d-411b-bbe0-xxxxxxxxxxxx', service = 'ads')
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: certificate has expired
```

Any advice on what I could try?

**Comment by khufkens** [comment]
Reinstall and try again, I fixed some issues and pushed just now. Unit tests now run nicely so things should work for you (or reboot R to be sure).

**Comment by khufkens** [comment]
FYI the example in the README landing page should work as this is what I use as a unit test.

**Comment by philament** [comment]
Hm, seems to be an issue with my local Mac installation. On my Windows machine everything works flawlessly (with the same credential as above), and I was able to download your example just fine. I will let you know if I find out what the problem is on the Mac.

**Comment by khufkens** [comment]
Ok, I'll close the issue but please let me know if you find what is wrong. It might help others as well. I can't test for every system.
