### ISSUE TITLE
MARS or python based query 

### ISSUE THREAD

**Issue by prenses95** [bluegreen-labs/ecmwfr#71]
Hello, I can't find the MARS or python based queries you mentioned in Data Requests. Can you help me find out how? I searched for ECMWF a lot, but still could not find it.

**Comment by khufkens** [comment]
Python request will show on CDS after hitting show API request
![cds](https://user-images.githubusercontent.com/1354258/93717712-e92de300-fb77-11ea-95c5-4b0f7742b1f4.png)

WebAPI request will show after hitting view data retrieval request
![ecmwf](https://user-images.githubusercontent.com/1354258/93717707-e16e3e80-fb77-11ea-914f-f9bd86a4a66a.png)

with the choice of python or MARS code
![ecmwf2](https://user-images.githubusercontent.com/1354258/93717738-0fec1980-fb78-11ea-8ba7-1cee2bf7c40a.png)

You need logins for both to show on the data search pages.

**Comment by prenses95** [comment]
Thanks a lot for the quick turnaround. I'm signing in on the page.
![image](https://user-images.githubusercontent.com/71181652/93718128-bb9a6700-fb82-11ea-9382-7c6c1b8485ad.png)
But still we could not find the MARS request. Because I can't find view data retrieval request either. Sorry I'm very new yet.

**Comment by khufkens** [comment]
You only need the c.retrieve(...) part and CDS does not have a MARS request, as per documentation. Use the python addin to translate this to a valid R query.

**Comment by prenses95** [comment]
Thank you. I asked in detail because I was wondering how I could see both :)
