### ISSUE TITLE
wf_request error

### ISSUE THREAD

**Issue by prenses95** [bluegreen-labs/ecmwfr#72]
wf_get_key (user = "5168x")
Error in b_wincred_i_get (target): Windows credential store error in 'get': Element not found.
using it it gives this error.

But when using wf_set_key, there is no problem.
> wf_set_key (user = "5168x",
+ key = "23a2dddd-cc98-431c-8a3e-d06713eaxxxx",
+ service = "cds")
User 5168x for cds service added successfully in keychain

When I try to run wf_request I get the following error.
file <- wf_request (user = "5168x",
+ request = request,
+ transfer = TRUE,
+ path = ".")

Error: Data identifier reanalysis-era5-single-level is not found in Web API, CDS or ADS datasets. Or your login credentials do not match your request.

Why do you think this is happening? I do everything according to what is written in the document.

**Comment by khufkens** [comment]
You have to specify the service.

```r
wf_get_key (user = "5168x", service = "cds")

```

**Comment by prenses95** [comment]
As I understand it is  not necessary to use wf_get_key. I registered when I used wf_set_key.  But I don't understand why it gives an error when I create a request?
Also, shouldn't the display in the setup section change?
   you can retrieve the key using
wf_get_key (user = "1234")
    
 Alternatively you can input your login info with an interactive request
wf_set_key (service = "cds")

**Comment by khufkens** [comment]
Can or can you not retrieve the data?

```r
wf_set_key(user = "test", key = "foo", service = "cds")
wf_get_key(user = "test", service = "cds")
```

If no key is returned correctly you can not create a request. You should then check if your keyring is correctly installed on Windows.

**Comment by prenses95** [comment]
I tried these and registration is successful.But it still gives the following error in the request.
Error: Data identifier reanalysis-era5-single-level is not found in Web API, CDS or ADS datasets.Or your login credentials do not match your request.
Should I check with the function wf_check_request if it is properly installed on Windows?  If so, I tried it and again I got the error "Error: Data identifier reanalysis-era5-single-level is not found in Web API, CDS or ADS datasets. Or your login credentials do not match your request".

**Comment by khufkens** [comment]
Then your request is faulty. Check the formatting and never hand code it.

**Comment by prenses95** [comment]
Thank you. I think i got it

**Comment by uchiavetta** [comment]
Hi there,

I fixed the issue with the following procedure:
- close RStudio
- download Rtools.exe from web and install it
- open Rstudio
- Update all packages (say OK to the request to "download from sources the compiled packages"... or something similar) and wait for this operation (may take a while!)
- Restar R session (maybe not nedded)

I hope this may be helpful!

**Comment by khufkens** [comment]
Thanks for the pointers. It's weird as my unit checks, which download data function well on Windows. Might be something really configuration specific.
