### ISSUE TITLE
request failure 

### ISSUE THREAD

**Issue by hydrovorobey** [bluegreen-labs/ecmwfr#75]
Data identifier XXX is not found in Web API, CDS or ADS datasets.  Or your login credentials do not match your request

Similar issue was already posted, but no solution found. Since yesterday I started to get this error (before there was no problems). Only thing I did - updated all libraries I use.
wf_get_key return my key (I tried 3 accounts already)
I tried 'reanalysis-era5-single-levels-preliminary-back-extension', 'reanalysis-era5-single-levels', 'seasonal-original-single-levels'

p.s. I even tried your example from github documentation
request <- list("dataset_short_name" = "reanalysis-era5-pressure-levels",
                "product_type" = "reanalysis",
                "variable" = "temperature",
                "pressure_level" = "850",
                "year" = "2000",
                "month" = "04",
                "day" = "04",
                "time" = "00:00",
                "area" = "70/-20/00/60",
                "format" = "netcdf",
                "target" = "era5-demo.nc")

My sample request (basically mimicking example above):
    request = list('dataset_short_name'=dataset_short_name,'product_type'='reanalysis','grid'='0.1/0.1',
                   'variable'=my_var,'date'=my_dates,'time'=my_time,'area'=my_area,
                   'format'='netcdf','target'=my_target)

Fun which check validity wf_check_request of request gives error itself
encl$`_hash`(c(encl$`_f_hash`, args, lapply(encl$`_additional`,  :  object 'rlang_hash' not found

R- version I use 4.0.3. 

p.s.2 after another re-update of all packages it works. sometimes. voodoo. maybe this is nothing to do with package itself then.

**Comment by khufkens** [comment]
Due to the inclusion of new data repositories the formatting of requests changed in the latest release as explained here:
https://github.com/bluegreen-labs/ecmwfr#stable-release

Reformat your request using the addin to fix this.

**Comment by khufkens** [comment]
If the build label is green you can be sure that most of the issues you encounter are request formatting issues. Always format your requests, from CDS python/MARS code, using the addin where possible. This is the single most common source of errors.
