### ISSUE TITLE
Failing with Soil Moisture dataset ?

### ISSUE THREAD

**Issue by danielreispereira** [bluegreen-labs/ecmwfr#91]
Trying to download the dataset at https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-soil-moisture?tab=form 
 with the following returns a BLANK error. Bug or am I doing something wrong ?

`request <- list("dataset"               = "satellite-soil-moisture",
                "variable"                       = "volumetric_surface_soil_moisture",
                "type_of_sensor"           = "combined_passive_and_active",
                "time_aggreagation"     =  "day_average",
                "year"                             = "2000",
                "month"                         = "01",
                "day"                              = "04",
                'type_of_record'             = 'icdr',
                "version"                        = "v202012.0.0",
                "format"                         = "tgz",
                "target"                          = "smos_ap.tar.gz")

#---Start downloading the data, the path of the file will be returned as a variable (ncfile)
ncfile <- wf_request(user = "NNNN",
                     request = request,   
                     transfer = TRUE,  
                     path = "/mnt/volume_sfo3_01/_dt_smos_ap_/",
                     verbose = TRUE)`

**Comment by khufkens** [comment]
This request works for me. Check your query. Also consider that the transfer might time out and you will need to download the data from the CDS requests page. Make sure that the output directory exists.

```r
library(ecmwfr)

request <- list(
  format = "zip",
  variable = "surface_soil_moisture",
  type_of_sensor = "active",
  time_aggregation = "day_average",
  year = "2016",
  month = "01",
  day = "01",
  version = "v201706.0.0",
  type_of_record = "cdr",
  dataset_short_name = "satellite-soil-moisture",
  target = "download.zip"
)

ncfile <- wf_request(user = X,
                     request = request,
                     transfer = TRUE,
                     path = "~/Desktop/",
                     verbose = TRUE)

```
